### UserModel Login

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "jason@gmail.com",
  "password": "password123"
}

### UserModel Login (Invalid)

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "jason@gmail.com",
  "password": "invalid_password"
}

### UserModel Profile (No token)
GET http://localhost:3000/api/user/profile

### UserModel Profile (Valid token)
GET http://localhost:3000/api/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imphc29uQGdtYWlsLmNvbSIsImlhdCI6MTU4MzI2MDgyN30.Iv1bGF28pfm81usNipMcXW4IXipFAjBGHtNXgIsCeN8

### Get Refresh Token
POST http://localhost:3000/api/session/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imphc29uQGdtYWlsLmNvbSIsImlhdCI6MTU4MzExMjg5NH0.qMdfXkVe1-zu8UPCnWUlByqQWZ9ID_ig6-4y25UvP_k"
}

###
